name: Create Pull Request on Version Update

on:
  push:
    branches: ["master"]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    # if: ${{ contains(github.event.head_commit.message, 'SOFTWARE VERSION UPDATED') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          ref: master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          title: "Merge master into develop"
          commit-message: "chore: SOFTWARE VERSION UPDATED"
          base: develop
          head: master
          delete-branch: true
          body: "Automatically created pull request to merge changes from the master branch into the develop branch."
