name: Create Pull Request on Version Update
on:
  push:
    branches: ["master"]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3

        with:
          title: "Merge master into develop"
          commit-message: "chore: SOFTWARE VERSION UPDATED"
          branch: develop
          body: "Automatically created pull request to merge changes from the master branch into the develop branch."
